security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: test123456
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      uri: mongodb://user:123456@localhost:27017/?authSource=piggymetrics
      database: piggymetrics

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true